version: '2.1'

services:
  proxy:
    image: nginx:alpine
    restart: always
    # Included NGINX config used hostname to determine what it's server_name will be 
    # Either set NGINX_HOSTNAME to it's public DNS name, change this line, or the config
    hostname: appteam-ctfscoreboard.joshcgrossman.com
    ports:
      - "80:8000"
      - "443:8443"
    volumes:
      - ./ssl:/etc/ssl:ro # Change this to match where your certificates are. Look at and adjust names in nginx.conf
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - .data/nginx/logs:/var/log/nginx
    networks:
      default:
      internal:
    depends_on:
      - ctfd
  
  ctfd:
    build: .
    restart: always
    expose:
      - "8000"
    environment:
      - UPLOAD_FOLDER=/var/uploads
      - LOG_FOLDER=/var/log/CTFd
      - USE_SSL=false
      - USE_RELOAD=false
      - DATABASE_URL=mysql+pymysql://root:ctfd@db/ctfd
    volumes:
      - .data/CTFd/logs:/var/log/CTFd
      - .data/CTFd/uploads:/var/uploads
      - .:/opt/CTFd:ro
    depends_on:
      - db
    networks:
      internal:
  
  db:
    image: mariadb:10.2
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=ctfd
      - MYSQL_USER=ctfd
      - MYSQL_PASSWORD=ctfd
    volumes:
      - .data/mysql:/var/lib/mysql
    networks:
        internal:
    # This command is required to set important mariadb defaults
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --wait_timeout=28800]

networks:
    default:
    internal:
        internal: true
